#Data Structures in Julia

## Using the data structures package

In [54]:
using DataStructures

### Deque - Double sided queues
The Deque type implements a double-ended queue using a list of blocks. This data structure supports constant-time insertion/removal of elements at both ends of a sequence.

In [55]:
a = Deque{Int}()
isempty(a)          # test whether the dequeue is empty
length(a)           # get the number of elements
push!(a, 10)        # add an element to the back
pop!(a)             # remove an element from the back
unshift!(a, 20)     # add an element to the front
shift!(a)           # remove an element from the front
front(a)            # get the element at the front
back(a)             # get the element at the back

LoadError: Attempted to front at an empty deque.
while loading In[55], in expression starting on line 8

In [57]:
a = Deque{Int}()

Deque [[]]

In [59]:
isempty(a)

true

In [63]:
push!(a,10)

Deque [[10,10]]

In [64]:
pop!(a)

10

In [65]:
unshift!(a, 20)

Deque [[20,10]]

In [66]:
shift!(a)

20

In [67]:
front(a)

10

In [68]:
back(a)

10

### Stacks and Queues
The Stack and Queue types are a light-weight wrapper of a deque type, which respectively provide interfaces for FILO and FIFO access.

In [70]:
s = Stack(Int)
push!(s, x)
x = top(s)
x = pop!(s)

LoadError: `convert` has no method matching convert(::Type{Int64}, ::Array{Float64,1})
while loading In[70], in expression starting on line 2

In [71]:
s = Stack(Int)

Stack{Deque{Int64}}(Deque [[]])

In [73]:
push!(s, 1)

Stack{Deque{Int64}}(Deque [[1]])

In [75]:
x = top(s)

1

In [80]:
println(length(s))

0


In [83]:
q = Queue(Int)
enqueue!(q, 1)

Queue{Deque{Int64}}(Deque [[1]])

In [84]:
x = front(q)
y = back(q)
println(x == y)

true


In [85]:
x = dequeue!(q)

1

###Disjoint Sets

In [86]:
a = IntDisjointSets(10)      # creates a forest comprised of 10 singletons
union!(a, 3, 5)             # merges the sets that contain 3 and 5 into one
in_same_set(a, x, y)        # determines whether x and y are in the same set
elem = push!(a)             # adds a single element in a new set; returns the new element
                            # (this operation is often called MakeSet)

11

In [ ]:
a = DisjointSets{String}(["a", "b", "c", "d"])
union!(a, "a", "b")
in_same_set(a, "c", "d")
push!(a, "f")

###Heaps
Heaps are data structures that efficiently maintain the minimum (or maximum) for a set of data that may dynamically change.

In [97]:
h = binary_maxheap(Int)

BinaryHeap{Int64,GreaterThan}(GreaterThan(),[])

In [98]:
h = binary_maxheap([12,234,2,512,5,235,25,12,512,5,234,4])

BinaryHeap{Int64,GreaterThan}(GreaterThan(),[512,512,235,234,234,4,25,12,12,5,5,2])

In [100]:
# Let h be a heap, i be a handle, and v be a value.

length(h)         # returns the number of elements

isempty(h)        # returns whether the heap is empty

push!(h, 1651)       # add a value to the heap

top(h)            # return the top value of a heap

pop!(h)           # removes the top value, and returns it

1651

In [102]:
h = mutable_binary_maxheap([2414,14,61,7,2345,25,17,5,123])

MutableBinaryHeap(2414, 2345, 61, 123, 14, 25, 17, 5, 7)

In [105]:
update!(h, 2, 12)

`nlargest(n, a)` is equivalent to `sort(a, lt = >)[1:min(n, end)]`, and `nsmallest(n, a)` is equivalent to `sort(a, lt = <)[1:min(n, end)]`.

In [108]:
function nlargest(n, a::Array{Int})
    return sort(a, lt = >)[1:min(n, end)]
end

nlargest (generic function with 1 method)

In [110]:
function nsmallest(n, a::Array{Int})
    return sort(a, lt= <)[1:min(n, end)]
end

nsmallest (generic function with 1 method)

In [114]:
nlargest(3, [1,2,3,4,5])

3-element Array{Int64,1}:
 5
 4
 3

In [115]:
nsmallest(3, [5,4,3,2,1])

3-element Array{Int64,1}:
 1
 2
 3

###OrderedDicts and OrderedSets
OrderedDicts are simply dictionaries whose entries have a particular order. For OrderedDicts (and OrderedSets), order refers to insertion order, which allows deterministic iteration over the dictionary or set:

In [118]:
d = OrderedDict{Char,Int}()
for c in 'a':'e'
    d[c] = c-'a'+1
end
collect(d)' # => [('a',1),('b',2),('c',3),('d',4),('e',5)]

1x5 Array{(Char,Int64),2}:
 ('a',1)  ('b',2)  ('c',3)  ('d',4)  ('e',5)

In [119]:
s = OrderedSet(π,e,γ,catalan,φ)
collect(s) # => [π = 3.1415926535897...,
           #     e = 2.7182818284590...,
           #     γ = 0.5772156649015...,
                 #     catalan = 0.9159655941772...,
                 #     φ = 1.6180339887498...]

5-element Array{Any,1}:
       π = 3.1415926535897...
       e = 2.7182818284590...
       γ = 0.5772156649015...
 catalan = 0.9159655941772...
       φ = 1.6180339887498...

###DefaultDict and DefaultOrderedDict
A DefaultDict allows specification of a default value to return when a requested key is not in a dictionary.

While the implementation is slightly different, a DefaultDict can be thought to provide a normal Dict with a default value. A DefaultOrderedDict does the same for an OrderedDict.

In [122]:
dd = DefaultDict(1)               # create an (Any=>Any) DefaultDict with a default value of 1
dd = DefaultDict(String, Int, 0)  # create a (String=>Int) DefaultDict with a default value of 0

d = ['a'=>1, 'b'=>2]
dd = DefaultDict(0, d)            # provide a default value to an existing dictionary
dd['c'] == 0                      # true
#d['c'] == 0                      # false

dd = DefaultOrderedDict(time)     # call time() to provide the default value for an OrderedDict
dd = DefaultDict(Dict)            # Create a dictionary of dictionaries
                                  # Dict() is called to provide the default value
dd = DefaultDict(()->myfunc())    # call function myfunc to provide the default value

# create a Dictionary of type String=>DefaultDict{String, Int}, where the default of the
# inner set of DefaultDicts is zero
dd = DefaultDict(String, DefaultDict, ()->DefaultDict(String,Int,0))

DefaultDict{String,DefaultDict{K,V,F},Function} with 0 entries

In [124]:
d['c'] = 3

3

In [125]:
d

Dict{Char,Int64} with 3 entries:
  'b' => 2
  'c' => 3
  'a' => 1

###Trie
An implementation of the Trie data structure. This is an associative structure, with String keys:

In [126]:
t=Trie{Int}()
t["Rob"]=42
t["Roger"]=24
haskey(t,"Rob") #true
get(t,"Rob",nothing) #42
keys(t) # "Rob", "Roger"

2-element Array{String,1}:
 "Rob"  
 "Roger"

In [132]:
#to test whether a trie contains any prefix of a given string, use:
seen_prefix(t::Trie, str) = any(v -> v.is_key, path(t, str))

seen_prefix (generic function with 1 method)

In [131]:
seen_prefix(t, "Rob")

true

###Linked List

In [134]:
l1 = nil()

nil()

In [135]:
l2 = cons(1, l1)

list(1)

In [137]:
l3 = list(2,3)

list(2, 3)

In [138]:
l4 = cat(l1, l2, l3)

list(1, 2, 3)

In [139]:
l5 = map((x) -> x*2, l4)

list(2, 4, 6)

In [144]:
for i in l5; println(i); end

2
4
6


#Buffon's Needle

In [3]:
function buffon(m)
    hit = 0
    for i = 1:m
        mp = rand()
        phi = (rand() * pi) - pi / 2
        xrechts = mp + cos(phi) / 2
        xlinks = mp - cos(phi) / 2
        if xrechts >= 1 || xlinks <= 0
            hit += 1
        end
    end
    miss = m - hit
    piapprox = m / hit * 2
end

buffon (generic function with 1 method)

In [34]:
"Time elapsed: " * string(@elapsed a = buffon(100000000)) * " seconds"

"Time elapsed: 4.659189982 seconds"

In [35]:
"Estimation for pi: " * string(a)

"Estimation for pi: 3.1416930423578924"

##Buffon's Needle in Parallel

In [7]:
function buffon_parallel(m)
    hit = @parallel (+) for i = 1:m
        mp = rand()
        phi = (rand() * pi) - pi / 2
        xrechts = mp + cos(phi) / 2
        xlinks = mp - cos(phi) / 2
        (xrechts >= 1 || xlinks <= 0) ? 1 : 0
    end
    miss = m - hit
    piapprox = m / hit * 2
end

buffon_parallel (generic function with 1 method)

In [31]:
"Time elapsed: " * string(@elapsed b = buffon_parallel(100000000)) * " seconds"

"Time elapsed: 4.610179443 seconds"

In [36]:
"Estimation for pi: " * string(b)

"Estimation for pi: 3.141909906393235"

In [37]:
function randmatstat(t; n=10)
 v = zeros(t)
 w = zeros(t)
 for i = 1:t
 a = randn(n,n)
 b = randn(n,n)
 c = randn(n,n)
 d = randn(n,n)
 P = [a b c d]
 Q = [a b; c d]
 v[i] = trace((P'*P)^4)
 w[i] = trace((Q'*Q)^4)
 end
 std(v)/mean(v), std(w)/mean(w)
end

randmatstat (generic function with 1 method)

In [38]:
randmatstat(100)

(0.35356334122197053,0.4004604306751935)

##Low Level Code

In [39]:
function qsort!(a,lo,hi)
 i, j = lo, hi
 while i < hi
 pivot = a[(lo+hi)>>>1]
 while i <= j
 while a[i] < pivot; i = i+1; end
 while a[j] > pivot; j = j-1; end
 if i <= j
 a[i], a[j] = a[j], a[i]
 i, j = i+1, j-1
 end
 end
 if lo < j; qsort!(a,lo,j); end
 lo, j = i, hi
 end
 return a
end

qsort! (generic function with 1 method)

In [45]:
c = randn(1000*1000, 100);

LoadError: interrupt
while loading In[45], in expression starting on line 1

##Using Python libraries within Julia

In [51]:
using PyCall
@pyimport math
math.sin(math.pi / 4) - sin(pi / 4)

0.0

In [52]:
@pyimport pylab
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
pylab.plot(x, y; color="red", linewidth=2.0, linestyle="--")
pylab.show()